"""empty message

Revision ID: 48873bf2d050
Revises: 2bdefbc60d10
Create Date: 2018-06-23 17:24:45.972880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48873bf2d050'
down_revision = '2bdefbc60d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.String(length=280), nullable=True))
    op.create_index(op.f('ix_post_url'), 'post', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_url'), table_name='post')
    op.drop_column('post', 'url')
    # ### end Alembic commands ###
