"""empty message

Revision ID: 563a985510fd
Revises: a447a10176ae
Create Date: 2018-06-15 17:23:13.574089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563a985510fd'
down_revision = 'a447a10176ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pined_msg_home_msg'), 'pined_msg', ['home_msg'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pined_msg_home_msg'), table_name='pined_msg')
    # ### end Alembic commands ###
