"""empty message

Revision ID: 602069fbcd72
Revises: ad61fb655bbe
Create Date: 2018-06-08 16:34:12.322069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602069fbcd72'
down_revision = 'ad61fb655bbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('secret_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_settings_secret_key'), 'settings', ['secret_key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_secret_key'), table_name='settings')
    op.drop_column('settings', 'secret_key')
    # ### end Alembic commands ###
