"""empty message

Revision ID: 91e8a402bc5b
Revises: 48873bf2d050
Create Date: 2018-07-07 18:49:18.283896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e8a402bc5b'
down_revision = '48873bf2d050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_url', sa.String(length=280), nullable=True))
    op.add_column('post', sa.Column('summary', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'summary')
    op.drop_column('post', 'img_url')
    # ### end Alembic commands ###
