"""new fields edit perfil in user model

Revision ID: 9c89df1fba92
Revises: 4651b81bf893
Create Date: 2018-04-24 17:30:46.749083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c89df1fba92'
down_revision = '4651b81bf893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('github', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('screen_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('twitter', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('website', sa.String(length=280), nullable=True))
    op.create_index(op.f('ix_user_github'), 'user', ['github'], unique=True)
    op.create_index(op.f('ix_user_screen_name'), 'user', ['screen_name'], unique=True)
    op.create_index(op.f('ix_user_twitter'), 'user', ['twitter'], unique=True)
    op.create_index(op.f('ix_user_website'), 'user', ['website'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_website'), table_name='user')
    op.drop_index(op.f('ix_user_twitter'), table_name='user')
    op.drop_index(op.f('ix_user_screen_name'), table_name='user')
    op.drop_index(op.f('ix_user_github'), table_name='user')
    op.drop_column('user', 'website')
    op.drop_column('user', 'twitter')
    op.drop_column('user', 'screen_name')
    op.drop_column('user', 'github')
    # ### end Alembic commands ###
