"""empty message

Revision ID: a405afb1d1a8
Revises: f59a9322967f
Create Date: 2018-06-16 18:39:20.662494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a405afb1d1a8'
down_revision = 'f59a9322967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pined_msg', sa.Column('blog_msg', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pined_msg', 'blog_msg')
    # ### end Alembic commands ###
