"""pinned msgs

Revision ID: a447a10176ae
Revises: 7b4f589967f6
Create Date: 2018-06-15 14:56:05.266484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a447a10176ae'
down_revision = '7b4f589967f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pined_msg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_msg', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pined_msg')
    # ### end Alembic commands ###
