"""empty message

Revision ID: a7801ec09cfd
Revises: 563a985510fd
Create Date: 2018-06-15 17:29:40.147409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7801ec09cfd'
down_revision = '563a985510fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pined_msg_home_msg', table_name='pined_msg')
    op.create_index(op.f('ix_pined_msg_home_msg'), 'pined_msg', ['home_msg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pined_msg_home_msg'), table_name='pined_msg')
    op.create_index('ix_pined_msg_home_msg', 'pined_msg', ['home_msg'], unique=1)
    # ### end Alembic commands ###
