"""empty message

Revision ID: ad61fb655bbe
Revises: fcee3d97d7ed
Create Date: 2018-06-07 20:23:13.003053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad61fb655bbe'
down_revision = 'fcee3d97d7ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=64), nullable=True),
    sa.Column('post_per_page', sa.Integer(), nullable=True),
    sa.Column('mail_server', sa.String(), nullable=True),
    sa.Column('mail_port', sa.Integer(), nullable=True),
    sa.Column('mail_use_tls', sa.Integer(), nullable=True),
    sa.Column('mail_username', sa.Integer(), nullable=True),
    sa.Column('mail_password', sa.Integer(), nullable=True),
    sa.Column('admins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_admins'), 'settings', ['admins'], unique=False)
    op.create_index(op.f('ix_settings_mail_password'), 'settings', ['mail_password'], unique=False)
    op.create_index(op.f('ix_settings_mail_port'), 'settings', ['mail_port'], unique=False)
    op.create_index(op.f('ix_settings_mail_server'), 'settings', ['mail_server'], unique=False)
    op.create_index(op.f('ix_settings_mail_use_tls'), 'settings', ['mail_use_tls'], unique=False)
    op.create_index(op.f('ix_settings_mail_username'), 'settings', ['mail_username'], unique=False)
    op.create_index(op.f('ix_settings_post_per_page'), 'settings', ['post_per_page'], unique=False)
    op.create_index(op.f('ix_settings_site_name'), 'settings', ['site_name'], unique=False)
    op.add_column('user', sa.Column('is_administrator', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_is_administrator'), 'user', ['is_administrator'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_administrator'), table_name='user')
    op.drop_column('user', 'is_administrator')
    op.drop_index(op.f('ix_settings_site_name'), table_name='settings')
    op.drop_index(op.f('ix_settings_post_per_page'), table_name='settings')
    op.drop_index(op.f('ix_settings_mail_username'), table_name='settings')
    op.drop_index(op.f('ix_settings_mail_use_tls'), table_name='settings')
    op.drop_index(op.f('ix_settings_mail_server'), table_name='settings')
    op.drop_index(op.f('ix_settings_mail_port'), table_name='settings')
    op.drop_index(op.f('ix_settings_mail_password'), table_name='settings')
    op.drop_index(op.f('ix_settings_admins'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
