"""Deleted Settings in DB

Revision ID: c9ce297c4c62
Revises: 602069fbcd72
Create Date: 2018-06-08 17:46:03.690596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ce297c4c62'
down_revision = '602069fbcd72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_settings_admins', table_name='settings')
    op.drop_index('ix_settings_mail_password', table_name='settings')
    op.drop_index('ix_settings_mail_port', table_name='settings')
    op.drop_index('ix_settings_mail_server', table_name='settings')
    op.drop_index('ix_settings_mail_use_tls', table_name='settings')
    op.drop_index('ix_settings_mail_username', table_name='settings')
    op.drop_index('ix_settings_post_per_page', table_name='settings')
    op.drop_index('ix_settings_secret_key', table_name='settings')
    op.drop_index('ix_settings_site_name', table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('post_per_page', sa.INTEGER(), nullable=True),
    sa.Column('mail_server', sa.VARCHAR(), nullable=True),
    sa.Column('mail_port', sa.INTEGER(), nullable=True),
    sa.Column('mail_use_tls', sa.INTEGER(), nullable=True),
    sa.Column('mail_username', sa.INTEGER(), nullable=True),
    sa.Column('mail_password', sa.INTEGER(), nullable=True),
    sa.Column('admins', sa.INTEGER(), nullable=True),
    sa.Column('secret_key', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_settings_site_name', 'settings', ['site_name'], unique=False)
    op.create_index('ix_settings_secret_key', 'settings', ['secret_key'], unique=False)
    op.create_index('ix_settings_post_per_page', 'settings', ['post_per_page'], unique=False)
    op.create_index('ix_settings_mail_username', 'settings', ['mail_username'], unique=False)
    op.create_index('ix_settings_mail_use_tls', 'settings', ['mail_use_tls'], unique=False)
    op.create_index('ix_settings_mail_server', 'settings', ['mail_server'], unique=False)
    op.create_index('ix_settings_mail_port', 'settings', ['mail_port'], unique=False)
    op.create_index('ix_settings_mail_password', 'settings', ['mail_password'], unique=False)
    op.create_index('ix_settings_admins', 'settings', ['admins'], unique=False)
    # ### end Alembic commands ###
