"""post blog

Revision ID: ffe35824c0cd
Revises: 0c62054fb83a
Create Date: 2018-04-28 16:31:21.033939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe35824c0cd'
down_revision = '0c62054fb83a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_github', table_name='user')
    op.create_index(op.f('ix_user_github'), 'user', ['github'], unique=False)
    op.drop_index('ix_user_screen_name', table_name='user')
    op.create_index(op.f('ix_user_screen_name'), 'user', ['screen_name'], unique=False)
    op.drop_index('ix_user_twitter', table_name='user')
    op.create_index(op.f('ix_user_twitter'), 'user', ['twitter'], unique=False)
    op.drop_index('ix_user_website', table_name='user')
    op.create_index(op.f('ix_user_website'), 'user', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_website'), table_name='user')
    op.create_index('ix_user_website', 'user', ['website'], unique=1)
    op.drop_index(op.f('ix_user_twitter'), table_name='user')
    op.create_index('ix_user_twitter', 'user', ['twitter'], unique=1)
    op.drop_index(op.f('ix_user_screen_name'), table_name='user')
    op.create_index('ix_user_screen_name', 'user', ['screen_name'], unique=1)
    op.drop_index(op.f('ix_user_github'), table_name='user')
    op.create_index('ix_user_github', 'user', ['github'], unique=1)
    # ### end Alembic commands ###
